server:
  port: 9000
  servlet:
    context-path: /interface
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alias_openapi?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 321998
  # sms service
  mail:
    host: smtp.qq.com
    username: zhexunchen@qq.com
    password: ualqybfjbbnhcaab
    default-encoding: utf-8